# Tugas Besar IF4074 - Pembelajaran Mesin Lanjut
# Implementasi Convolutional Neural Network

# Simple CNN
**Simple CNN** is a convolutional neural network implemented in Python and fine-tuned using backpropagation algorithm.

## Setup
Assuming you've installed the latest version of Python (if not, guides for it are widely available),
1. ensure pip is installed by running `python -m ensurepip --upgrade`;
2. install the Python dependencies by running `pip install -r requirements.txt`.

## Contribution (Milestone 1)
| NIM      | Name                   | Contribution(s)                                                       |
|----------|------------------------|-----------------------------------------------------------------------|
| 13520041 | Ilham Pratama          | Dataset handling; Detector, Pooling, Dense, and Flatten layer; Report |
| 13520042 | Jeremy S.O.N. Simbolon | Class model; Convolutional layer; Report                              |

## Contribution (Milestone 2)
| NIM      | Name                   | Contribution(s) |
|----------|------------------------|-----------------|
| 13520041 | Ilham Pratama          | -               |
| 13520042 | Jeremy S.O.N. Simbolon | -               |

### Library Import

In [6]:
import math
import os

from typing import Any

import cv2
import jsonpickle
import jsonpickle.ext.numpy
import numpy as np
import numpy.typing as npt

from scipy.special import expit
from sklearn import metrics

### Dataset Loading

In [7]:
class Utils:
    """
    Module related utility functions.

    This class is used to prepare the image dataset for the CNN model. In
    addition, this class is also used to save and load the CNN model.
    """

    @staticmethod
    def load_dataset(dataset_path: str) -> tuple[npt.NDArray, npt.NDArray, dict]:
        """
        Preprocess the dataset and return useful information for further processing.

        :param dataset_path: A string representation of the path pointing to
                             the dataset.
        :return: A tuple consisted of an ndarray of dataset image path, an
                 ndarray of image labels, and a dictionary that maps class
                 labels to folder name.
        """
        folder_list = sorted(os.listdir(dataset_path))
        image_path = []
        image_label = np.array([], dtype=np.int16)
        image_dictionary = {}
        for i, folder_name in enumerate(folder_list):
            class_folder_path = os.path.join(dataset_path, folder_name)
            list_image_name = sorted(os.listdir(class_folder_path))
            temp_folder_path = [os.path.join(class_folder_path, image_name) for image_name in list_image_name]

            image_path += temp_folder_path
            temp_class_label = np.full(len(list_image_name), i, dtype=np.int16)
            image_label = np.concatenate((image_label, temp_class_label), axis=0)
            image_dictionary[str(i)] = folder_name

        return np.asarray(image_path), image_label, image_dictionary

    @staticmethod
    def convert_image_to_matrix(path: npt.NDArray) -> npt.NDArray:
        """
        Convert the image dataset into a list of ndarray.

        Each ndarray is an RGB representation of each image in the dataset.

        :param path: An ndarray of string representation of the path pointing
                     to each image entry in the dataset.
        :return: A list of ndarray representation of the image in the dataset.
        """
        list_of_image_matrix = []
        size = (256, 256)

        for file_img in path:
            image = cv2.imread(file_img, 1)
            matrix = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
            matrix = cv2.resize(matrix, size)
            list_of_image_matrix.append(matrix)

        return np.array(list_of_image_matrix)

    @staticmethod
    def save_model(model_object: "Model", file_name: str = "model.json") -> None:
        """
        Save the specified model into a JSON file.

        :param model_object: The model to be saved.
        :param file_name: A string specifying the file name of the saved model.
        """
        jsonpickle.ext.numpy.register_handlers()
        with open(file_name, "w") as file:
            json = jsonpickle.encode(model_object, indent=4)
            file.write(json)

    @staticmethod
    def load_model(file_name: str = "model.json") -> "Model":
        """
        Load a model from the specified JSON file name.

        :param file_name: A string specifying the file name of the model to be
                          loaded.
        :return: The loaded model from the specified file.
        """
        jsonpickle.ext.numpy.register_handlers()
        with open(file_name, "r") as file:
            json = file.read()
            return jsonpickle.decode(json)

### Model Representation

In [8]:
class Model:
    """
    The convolutional neural network model used to classify images.
    """

    def __init__(self) -> None:
        """
        Instantiate the convolutional neural network model.
        """
        self._layers = []
        self._results = []

    class Layer:
        """
        Base representation of the layer used as part of the convolutional
        neural network architecture.
        """

        def __init__(self, name) -> None:
            """
            Instantiate the base layer.

            :param name: Name of the layer.
            """
            self._name = name

        def forward_propagate(self) -> None:
            """Indicate the forward propagation is being performed."""
            print(f"Performing forward propagation on {self._name} layer...")
            print()

        def backward_propagate(self) -> None:
            """Indicate the backward propagation is being performed."""
            print(f"Performing backward propagation on {self._name} layer...")
            print()

    class ConvolutionLayer(Layer):
        """
        The convolutional layer in convolutional neural network.

        This class is inherited from the ``Layer`` class. This layer is used
        to perform the convolution operation on the input weights.
        """

        def __init__(
            self,
            filter_count: int,
            filter_size: tuple[int, int] = (32, 32),
            padding_size: int = 0,
            stride_size: tuple[int, int] = (1, 1),
        ) -> None:
            """
            Instantiate the convolutional layer.

            :param filter_count: An integer specifying the amount of feature
                                 to be extracted in the form of the amount of
                                 filters.
            :param filter_size: A tuple of two integers specifying the height
                                and width of the convolution filter.
            :param padding_size: An integer specifying the dimension of 0's to
                                 be added around the weight.
            :param stride_size: A tuple of two integers specifying the pixel
                                step size along the height and width of the
                                input weight.
            """
            super().__init__("convolution")
            self._filter_count = filter_count
            self._filter_dimension = 0
            self._filter_height, self._filter_width = filter_size
            self._filter_weights = None
            self._padding_size = padding_size
            self._stride_height, self._stride_width = stride_size
            self._output_height = 0
            self._output_width = 0
            self._weight_dimension = 0
            self._weight_height = 0
            self._weight_width = 0
            self._weights = None
            self._biases = None
            self._filter_gradients = []
            self._bias_gradients = []

        def _pad_weights(
            self,
            weights: npt.NDArray[npt.NDArray[npt.NDArray[float]]],
            padding_size: int,
            forward: bool = True
        ) -> npt.NDArray[npt.NDArray[npt.NDArray[float]]]:
            """
            Pad the specified weights with 0's around it.

            :param weights: The ndarray of weights to be padded with 0's.
            :param padding_size: An integer specifying the dimension of 0's to
                                 be added around the weight.
            :param forward: A boolean specifying whether the padding is 
                            performed during forward propagation.
            :return: An ndarray of weights padded with 0's.
            """
            weight_dimension = len(weights)
            weight_height = len(weights[0])
            weight_width = len(weights[0][0])
            
            if forward:
                self._weight_dimension = weight_dimension
                self._weight_height = weight_height + 2 * padding_size
                self._weight_width = weight_width + 2 * padding_size

            padded_weights = [
                [
                    [
                        weights[i][j - padding_size][k - padding_size]
                        if padding_size <= j < weight_height + padding_size
                        or padding_size <= k < weight_width + padding_size
                        else 0.0
                        for k in range(weight_width + 2 * padding_size)
                    ]
                    for j in range(weight_height + 2 * padding_size)
                ]
                for i in range(weight_dimension)
            ]

            return np.array(padded_weights)

        def convolute(
            self,
            weights: npt.NDArray[npt.NDArray[npt.NDArray[float]]],
        ) -> npt.NDArray[npt.NDArray[npt.NDArray[float]]]:
            """
            Perform the convolution operation on the input weights.

            :param weights: An ndarray of input weights.
            :return: An ndarray of features extracted from the weights.
            """
            self._weights = weights
            self._filter_dimension = len(weights)
            self._output_height = (
                math.ceil((len(weights[0]) - self._filter_height + 2 * self._padding_size) / self._stride_height) + 1
            )
            self._output_width = (
                math.ceil((len(weights[0][0]) - self._filter_width + 2 * self._padding_size) / self._stride_width) + 1
            )

            if self._filter_weights is None:
                self._filter_weights = np.random.rand(
                    self._filter_count,
                    self._filter_dimension,
                    self._filter_height,
                    self._filter_width,
                )
            if self._biases is None:
                self._biases = np.random.rand(self._filter_count, self._output_height, self._output_width)

            feature_maps = np.copy(self._biases)
            weights = self._pad_weights(weights, self._padding_size)
            for i in range(self._filter_count):
                for j in range(0, self._weight_height - self._filter_height + 1, self._stride_height):
                    for k in range(0, self._weight_width - self._filter_width + 1, self._stride_width):
                        for l in range(self._filter_dimension):
                            field = weights[l, j : j + self._filter_height, k : k + self._filter_width]
                            feature = field * self._filter_weights[i][l]
                            feature_maps[i][j][k] += np.sum(feature)
            return feature_maps

        def calculate_error(self, output_gradient: npt.NDArray) -> npt.NDArray:
            output_gradient_height = len(output_gradient[0])
            output_gradient_width = len(output_gradient[0][0])
            
            filter_gradient = np.zeros((self._filter_count, self._filter_dimension, self._filter_height, self._filter_width))
            input_gradient = np.zeros((self._weight_dimension, self._weight_height, self._weight_width))
            padded_output_gradient = self._pad_weights(output_gradient, 2, forward=False)

            for i in range(self._filter_count):
                for j in range(self._filter_dimension):
                    for k in range(0, self._weight_height - output_gradient_height + 1, self._stride_height):
                        for l in range(0, self._weight_width - output_gradient_width + 1, self._stride_width):
                            field = self._weights[j, k : k + output_gradient_height, l : l + output_gradient_width]
                            gradient = field * output_gradient[i]
                            filter_gradient[i][j] = np.sum(gradient)
                    for k in range(0, output_gradient_height - self._filter_height + 1, self._stride_height):
                        for l in range(0, output_gradient_width - self._filter_width + 1, self._stride_width):
                            field = padded_output_gradient[i, k : k + self._filter_height, l : l + self._filter_width]
                            gradient = field * np.rot90(self._filter_weights[i][j], k=2)
                            input_gradient[j] += np.sum(gradient)
            
            self._filter_gradients.append(filter_gradient)
            self._bias_gradients.append(output_gradient)
            
            return input_gradient
        
        def update_weight(self, learning_rate: float) -> None:
            self._filter_weights -= learning_rate * np.average(np.array(self._filter_gradients), axis=0)
            self._biases -= learning_rate * np.average(np.array(self._bias_gradients), axis=0)
            self._filter_gradients = []
            self._bias_gradients = []

        def forward_propagate(
            self, weights: npt.NDArray[npt.NDArray[npt.NDArray[float]]]
        ) -> npt.NDArray[npt.NDArray[npt.NDArray[float]]]:
            """
            Indicate and perform the convolution process on the input weights.

            :param weights: The ndarray of weights to be convoluted.
            :return: An ndarray of convoluted weights.
            """
            super().forward_propagate()
            result = self.convolute(weights)
            print("Convolution result: ")
            print(result)
            print()
            return result

        def backward_propagate(self) -> npt.NDArray:
            """
            Indicate and perform the backward propagation operation on the model.
            """
            pass

    class DetectorLayer(Layer):
        """
        The detector layer in convolutional neural network.

        This class is inherited from the ``Layer`` class. This layer is used to
        introduce non-linearity to the learning process using the reLU
        activation function.
        """

        def __init__(self) -> None:
            """Instantiate the detector layer."""
            super().__init__("detector")

        # @staticmethod
        def detect(self, feature: npt.NDArray) -> npt.NDArray:
            """
            Apply the reLU activation function on the input weights.

            :param feature: An ndarray of input weights.
            :return: An ndarray of weights on which the reLU function has been
                     applied.
            """
            self.input = feature
            return np.maximum(feature, 0)

        def forward_propagate(self, feature: npt.NDArray) -> npt.NDArray:
            """
            Indicate and perform the detector process on the input weights.

            :param feature: The ndarray of weights on which reLU function is
                            to be applied.
            :return: An ndarray of activated weights.
            """
            super().forward_propagate()
            result = self.detect(feature)
            print("Detector result: ")
            print(result)
            print()
            return result

        def backward_propagate(self) -> npt.NDArray:
            """
            Indicate and perform the backward propagation operation on the model.
            """
            pass

        def backward(self, error: npt.NDArray) -> npt.NDArray:
            """
            Perform the backward propagation on the detector layer.
            Using Relu derivative : dReLU/dx = 1 if x > 0, otherwise 0

            :param error: The gradient from the next layer.
            :return: The gradient for the previous layer.
            """
            dX = error * (self.input > 0)
            return dX

    class PoolingLayer(Layer):
        """
        The pooling layer in convolutional neural network.

        This class is inherited from the ``Layer`` class. This layer is used to
        down-sample the input weights according to the specified pooling
        operation.
        """

        def __init__(self, filter_size: int, stride_size: int, mode: str = "max") -> None:
            """
            Instantiate the pooling layer.

            :param filter_size: An integer specifying the dimension of the
                                pooling window.
            :param stride_size: An integer specifying the pixel step size along
                                the height and width of the input weight.
            :param mode: A string specifying the preferred pooling operation.
                         Must either be ``average`` or ``max``.
            """
            super().__init__("pooling")
            self._filter_size = filter_size
            self._stride_size = stride_size
            self._mode = mode

        def average(self, input_matrix: npt.NDArray, d: int, h: int, w: int) -> float:
            """
            Take the average of the input values over the pooling window.

            :param input_matrix: The ndarray of weights on which the operation
                                 is applied.
            :param d: An integer specifying the depth location of the pooling
                      window.
            :param h: An integer specifying the height location of the pooling
                      window.
            :param w: An integer specifying the width location of the pooling
                      window.
            :return: The average of the input values.
            """
            h_start = h * self._stride_size
            w_start = w * self._stride_size
            h_end = h_start + self._filter_size
            w_end = w_start + self._filter_size
            return np.average(input_matrix[d, h_start:h_end, w_start:w_end])

        def max(self, input_matrix: npt.NDArray, d: int, h: int, w: int) -> float:
            """
            Take the maximum of the input values over the pooling window.

            :param input_matrix: The ndarray of weights on which the operation
                                 is applied.
            :param d: An integer specifying the depth location of the pooling
                      window.
            :param h: An integer specifying the height location of the pooling
                      window.
            :param w: An integer specifying the width location of the pooling
                      window.
            :return: The maximum of the input values.
            """
            h_start = h * self._stride_size
            w_start = w * self._stride_size
            h_end = h_start + self._filter_size
            w_end = w_start + self._filter_size
            return np.max(input_matrix[d, h_start:h_end, w_start:w_end])

        def pool(self, input_matrix: npt.NDArray) -> npt.NDArray:
            """
            Perform the pooling operation on the input weights.

            :param input_matrix: An ndarray of input weights.
            :return: An ndarray of down-sampled weights.
            """
            self.input = input_matrix
            depth, height, width = input_matrix.shape
            filter_height = (height - self._filter_size) // self._stride_size + 1
            filter_width = (width - self._filter_size) // self._stride_size + 1
            pooled = np.zeros([depth, filter_height, filter_width], dtype=np.double)
            for d in range(0, depth):
                for h in range(0, filter_height):
                    for w in range(0, filter_width):
                        if self._mode == "average":
                            pooled[d, h, w] = self.average(input_matrix, d, h, w)
                        elif self._mode == "max":
                            pooled[d, h, w] = self.max(input_matrix, d, h, w)
            return pooled

        def forward_propagate(self, input_matrix: npt.NDArray) -> npt.NDArray:
            """
            Indicate and perform the pooling operation on the input weights.

            :param input_matrix: An ndarray of input weights.
            :return: An ndarray of down-sampled weights.
            """
            super().forward_propagate()
            result = self.pool(input_matrix)
            print("Pooling result: ")
            print(result)
            print()
            return result

        def backward_propagate(self, error) -> npt.NDArray:
            """
            Indicate and perform the backward propagation operation on the model.
            """
            pass

        def backward(self, error):
            f, w, h = self.input.shape
            dx = np.zeros(self.input.shape)
            for i in range(0, f):
                for j in range(0, w, self._filter_size):
                    for k in range(0, h, self._filter_size):
                        input_slice = self.input[i, j : j + self._filter_size, k : k + self._filter_size]
                        max_input_slice = np.argmax(input_slice)
                        max_idx = np.unravel_index(max_input_slice, (self._filter_size, self._filter_size))
                        if (j + max_idx[0]) < w and (k + max_idx[1]) < h:
                            dx[i, j + max_idx[0], k + max_idx[1]] = error[
                                i, int(j // self._filter_size), int(k // self._filter_size)
                            ]
            return dx

    class DenseLayer(Layer):
        """
        The dense layer in convolutional neural network.

        This class is inherited from the ``Layer`` class. This layer is used to
        abstractly represent the input data using its weights.
        """

        def __init__(self, unit_count: int, activation: str = "sigmoid") -> None:
            """
            Instantiate the dense layer.

            :param unit_count: An integer specifying the dimension of the
                               output space.
            :param activation: The activation function to be applied to each
                               node. Must either be ``sigmoid`` or ``relu``.
            """
            super().__init__("dense")
            self._unit_count = unit_count
            self._activation = activation
            self._bias = np.zeros(unit_count)
            self._weight = []
            self._deltaW = np.zeros(unit_count)

        def dense(self, input_matrix: npt.NDArray) -> npt.NDArray:
            """
            Perform the linear combination and activation of the input weights
            using the layer's weights.

            :param input_matrix: An ndarray of input weights.
            :return: An ndarray of linearly-combined and activated weights.
            """
            self.input = input_matrix
            if len(self._weight) == 0:
                self._weight = np.random.randn(self._unit_count, len(self.input))
            result = np.zeros(self._unit_count)

            for i in range(self._unit_count):
                input_weight = np.sum(self._weight[i] * input_matrix)
                result[i] = input_weight + self._bias[i]

            if self._activation == "sigmoid":
                self.output = expit(result)
            elif self._activation == "relu":
                self.output = np.maximum(result, 0)
            return self.output

        def forward_propagate(self, input_matrix: npt.NDArray) -> npt.NDArray:
            """
            Indicate and perform the linear combination and activation of the
            input weights using the layer's weights.

            :param input_matrix: An ndarray of input weights.
            :return: An ndarray of linearly-combined and activated weights.
            """
            super().forward_propagate()
            result = self.dense(input_matrix)
            print("Dense result: ")
            print(result)
            print()
            return result

        def backward_propagate(self, error) -> npt.NDArray:
            """
            Indicate and perform the backward propagation operation on the model.
            """
            pass

        def backward(self, error) -> npt.NDArray:
            """
            Perform the backward propagation on the layer.

            :param error: The gradient from the next layer.
            :return: The gradient for the previous layer.
            """
            derivative_value = np.array([])
            for i in self.output:
                derivative_value = np.append(derivative_value, self.derivative_act_func(self._activation, i))

            self._deltaW += np.multiply(derivative_value, error)
            dE = np.matmul(error, self._weight)
            return dE

        def update_weight(self, learning_rate) -> None:
            """
            Indicate and perform the update weight and bias on the model
            """
            for i in range(self._unit_count):
                self._weight[i] = self._weight[i] - (learning_rate * self._deltaW[i] * self.input)

            self._bias = self._bias - (learning_rate * self._deltaW)
            self._deltaW = np.zeros(self._unit_count)

        def derivative_act_func(self, activation, input_):
            """
            Take derivative value from activation function and input
            """
            if activation == "sigmoid":
                return self.sigmoid_detivative(input_)
            else:
                return self.relu_derivative(input_)

        @staticmethod
        def sigmoid_derivative(input_):
            """
            Take derivative value from input
            """
            sigmoid = 1 / (1 + np.exp(-input_))
            return sigmoid * (1 - sigmoid)

        @staticmethod
        def relu_derivative(input_):
            """
            Take derivative value from input
            """
            if input_ >= 0:
                return 1
            else:
                return 0

    class FlattenLayer(Layer):
        """
        The flatten layer in convolutional neural network.

        This class is inherited from the ``Layer`` class. This layer is used to
        flatten the input weights.
        """

        def __init__(self) -> None:
            """Instantiate the flatten layer."""
            super().__init__("flatten")

        @staticmethod
        def flatten(input_matrix: npt.NDArray) -> npt.NDArray:
            """
            Perform the flatten operation on the input weights.

            :param input_matrix: An ndarray of input weights.
            :return: An ndarray of flatten weights.
            """
            return input_matrix.flatten()

        def forward_propagate(self, input_matrix: npt.NDArray) -> npt.NDArray:
            """
            Indicate and perform the flatten operation on the input weights.

            :param input_matrix: An ndarray of input weights.
            :return: An ndarray of flatten weights.
            """
            super().forward_propagate()
            result = self.flatten(input_matrix)
            print("Flatten result: ")
            print(result)
            print()
            return result

        def backward_propagate(self) -> npt.NDArray:
            """
            Indicate and perform the backward propagation operation on the model.
            """
            pass

    def add_layer(self, name: str, **kwargs: Any) -> None:
        """
        Sequentially add the specified layer into the model.

        :param name: A string representation of the layer to be added.
        :param kwargs: Layer-related parameters in the form of key-value pairs.
        """
        match name:
            case "convolution":
                self._layers.append(self.ConvolutionLayer(**kwargs))
            case "detector":
                self._layers.append(self.DetectorLayer())
            case "pooling":
                self._layers.append(self.PoolingLayer(**kwargs))
            case "dense":
                self._layers.append(self.DenseLayer(**kwargs))
            case "flatten":
                self._layers.append(self.FlattenLayer())

    def forward_propagate(self, tensor: npt.NDArray) -> None:
        """
        Indicate and perform the forward propagation operation on the model.

        :param tensor: An ndarray of input weights representing the input
                       pictures.
        """
        for layer in self._layers:
            tensor = layer.forward_propagate(tensor)
        print("Forward propagation result: ")
        print(tensor)
        self._results = tensor

    def backward_propagate(self) -> None:
        """
        Indicate and perform the backward propagation operation on the model.
        """
        self._backward_result = None
        pass

    def train(
        self,
        tensor: npt.NDArray[npt.NDArray],
        target: npt.NDArray,
        epochs: int = 1,
        batch_size: int = 5,
        learning_rate: float = 0.01,
    ) -> None:
        """
        Fit and train the CNN model.

        :param tensor: An ndarray of representations of the input pictures to
                       be fed into the model.
        :param target: An ndarray of representations of the target pictures to
                       be fed into the model.
        :param epochs: An integer specifying the number of training epochs.
        :param batch_size: An integer specifying the number of training batch.
        :param learning_rate: A float specifying the learning rate of the model.
        """
        out = np.array([])
        y_target = np.array([])
        for epoch in range(epochs):
            loss = 0
            print("Epoch : ", epoch + 1)
            for i in range(len(tensor)):
                self.forward_propagate(tensor[i])
                forward_result = self._results
                curr_target = target[i]
                curr_output = forward_result[0]
                dE = np.array([curr_target - curr_output]) * -1
                self.backward_propagate(dE)
                loss += 0.5 * (curr_target - curr_output) ** 2
                out = np.rint(np.append(out, curr_output))
                y_target = np.append(y_target, curr_target)

                # ketika sudah mencapai akhir dari batch update weightnya
                if (i + 1) % batch_size == 0:
                    for layer in reversed(self._layers):
                        layer.update_weight(learning_rate)

            avg_loss = loss / len(tensor)
            print("Loss: ", avg_loss)
            print("Accuracy: ", metrics.accuracy_score(y_target, out))

### Test result

In [9]:
folder_path, class_label, class_dictionary = Utils.load_dataset("./dataset")
image_matrix = Utils.convert_image_to_matrix(folder_path)
image_number = 0
image_matrix = [image_matrix[image_number]]

model = Model()
model.add_layer(
    "convolution",
    filter_count=32,
    filter_size=(3, 3),
    padding_size=0,
    stride_size=(1, 1),
)
model.add_layer("detector")
model.add_layer("pooling", filter_size=3, stride_size=2, mode="average")
model.add_layer("flatten")
model.add_layer("dense", unit_count=8, activation="relu")
model.add_layer("dense", unit_count=1, activation="sigmoid")
model.forward_propagate(image_matrix)

Performing forward propagation on convolution layer...

Convolution result: 
[[[ 549.29001939  540.12761152  537.62317567 ...  520.26862839
    515.92903654  516.91215601]
  [ 541.35055545  535.46095942  535.16095583 ...  520.76202737
    517.03218064  517.17131029]
  [ 539.62599808  534.50748302  536.39326033 ...  521.40666455
    517.59355828  517.23080858]
  ...
  [ 219.88770392  164.52454597  131.72043236 ...   23.0516546
     45.89508213  122.64506879]
  [ 202.43375699  114.8488342    83.77102647 ...   48.22645193
     72.750218    146.23311602]
  [ 129.03189531   57.76150697   41.05349154 ...   70.24052913
     85.75162477  132.67993539]]

 [[ 839.91222871  828.52905545  824.71496353 ...  792.40231259
    787.44444685  790.98079594]
  [ 829.50454303  821.99714408  822.04236944 ...  794.40338993
    789.33881196  792.60131227]
  [ 824.2717663   819.49842501  821.73678084 ...  796.46853097
    791.92797621  793.46418736]
  ...
  [ 371.5234435   270.97630993  184.09054619 ...   41.4

In [10]:
input_data = np.array([[[-10, 2], [5, -5]]])


model = Model()
detect = model.DetectorLayer()
detect_f = detect.detect(input_data)
print(detect_f)

err = np.array([[[-5, 2], [5, 4]]])

back_f = detect.backward(err)
print(back_f)

[[[0 2]
  [5 0]]]
[[[0 2]
  [5 0]]]


In [11]:
# Max pooling testing
input_data = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]])
polingLayer = model.PoolingLayer(2, 2)
pol_result_f = polingLayer.pool(input_data)
print("hasil pooling forward")
print(pol_result_f)

print("hasil pooling backward")
error_data = np.array([[[2, 1], [1, 2]]])

print(polingLayer.backward(error_data))

hasil pooling forward
[[[ 6.  8.]
  [14. 16.]]]
hasil pooling backward
[[[0. 0. 0. 0.]
  [0. 2. 0. 1.]
  [0. 0. 0. 0.]
  [0. 1. 0. 2.]]]


In [12]:
# Dense layer testing
denseLayer1 = Model().DenseLayer(unit_count=3, activation="sigmoid")
denseLayer = Model().DenseLayer(unit_count=1, activation="relu")
flatLayer = Model().FlattenLayer()
flat_f = flatLayer.flatten(pol_result_f)
dense_f1 = denseLayer1.dense(flat_f)
dense_f = denseLayer.dense(dense_f1)

print("bobot awal : ")
print(denseLayer._weight)

print("bias awal : ")
print(denseLayer._bias)

print("\n")
print("hasil forward1 : ")
print(dense_f1)

print("hasil forward2 : ")
print(dense_f)

print("\n")
print("hasil backward")

# error_data = np.array([0.1, -0.2, 0.3])
error_data = np.array([0.01])
# Backward propagation
dE = denseLayer.backward(error_data)
print("hasil dE : ")
print(dE)

# Update bobot lapisan
lr = 0.1
denseLayer.update_weight(lr)
print("bobot update : ")
print(denseLayer._weight)
print("bias update : ")
print(denseLayer._bias)

bobot awal : 
[[ 0.63946067 -0.59992825  1.80377072]]
bias awal : 
[0.]


hasil forward1 : 
[3.33840786e-10 1.35222561e-16 1.39767048e-04]
hasil forward2 : 
[0.00025211]


hasil backward
hasil dE : 
[ 0.00639461 -0.00599928  0.01803771]
bobot update : 
[[ 0.06394607 -0.05999282  0.18037693]]
bias update : 
[-0.001]
